tunnel: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
credentials-file: /home/ubuntu/.cloudflared/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.json

ingress:
  - hostname: yourtunnelhostnamedomain.abc
    service: http://localhost:3000
    originRequest:
      noTLSVerify: true
  - service: http_status:404
  
